### ISSUE TITLE
Type error.

### ISSUE THREAD

**Issue by daimajia** [bjarneo/extract-domain#28]
```node
- info Linting and checking validity of types ../node_modules/.pnpm/extract-domain@4.1.0/node_modules/extract-domain/index.ts:85:9
Type error: Type 'Promise<string | null>' is not assignable to type 'string | Promise<string>'.
  Type 'Promise<string | null>' is not assignable to type 'Promise<string>'.
    Type 'string | null' is not assignable to type 'string'.
      Type 'null' is not assignable to type 'string'.

  83 |         }
  84 | 
> 85 |         return import('psl')
     |         ^
  86 |             .then((psl) => Promise.resolve(psl.get(url.slice(offsetStart, offsetPath))))
  87 |             .catch((error) => {
  88 |                 console.error(error);

```

**Comment by bjarneo** [comment]
Thank you for the issue.

Where exactly do you get this error? 

Been testing in a typescript project, and can't seem to replicate this.

**Comment by rwxjon** [comment]
Hello! i have the same problem. I tried to build my App and i got that error

```
node_modules/extract-domain/index.ts(85,23): error TS7016
  Try npm i --save-dev @types/psl if it exists or add a new declaration (.d.ts) file containing declare module 'psl';
```

and if i install the types i get an error just like @daimajia 

```
node_modules/extract-domain/index.ts(85,9): error TS2322: Type 'Promise<string | null>' is not assignable to type 'string | Promise<string>'.

  Type 'Promise<string | null>' is not assignable to type 'Promise<string>'.

    Type 'string | null' is not assignable to type 'string'.

      Type 'null' is not assignable to type 'string'.
```


im using

node: 18
extract-domain: 2.3.1
typescript: 5.2.2

**Comment by bjarneo** [comment]
I did a quick fix on this, could you try the latest release? I managed to get the same error message, and solved that one. @JonPV @daimajia

**Comment by daimajia** [comment]
> I did a quick fix on this, could you try the latest release? I managed to get the same error message, and solved that one. @JonPV @daimajia 

Btw why **await** is required when tld is true? I think it can be designed as a synchronized function.

**Comment by bjarneo** [comment]
I agree with you here @daimajia. Using both sync and async is a really bad API design here. Same applies for possibility to pass an array with URLs and not only just a URL.


This is really how I would like the function to behave for the best developer experience.
```js
const domain = extractDomain('https://www.thisisatld.co.uk', { tld: true })
```

So, the reason it went from sync to async was due to the use of `import()`, and I am quite sure it is not possible to run import sync?

If you have any suggestions @daimajia, let me know. I am all up for changing the design and release a version 5.

EDIT: I would also like to add the main reason for calling it with import is due to I do not want to bundle the PSL library if it is not used. However, while thinking of it, it is possible to tree shake it.

**Comment by rwxjon** [comment]
@bjarneo  the error no longer appears! thank you very much!

**Comment by daimajia** [comment]
Why not just import pls library by default instead of an option.

**Comment by bjarneo** [comment]
Because that will increase the bundle size by 130kb: https://bundlephobia.com/package/psl@1.9.0, as long as it is not treeshaked, that is.
